apiVersion: v1
kind: Service
metadata:
  name: {{ template "gestion-evenement.fullname" . }}-postgres
  labels:
    app: {{ template "gestion-evenement.name" . }}-postgres
    chart: {{ template "gestion-evenement.chart" . }}-postgres
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ template "gestion-evenement.name" . }}-postgres
    release: {{ .Release.Name }}
