apiVersion: v1
kind: PersistentVolume
metadata:
  name: grav-pages
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /zpool-126262/WWWGRAV/pages
    server: 10.16.103.9
  persistentVolumeReclaimPolicy: Recycle