dependencies:
  - name: filebeat
    version: "1.0.2"
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: elasticsearch
    version: "1.13.1"
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: kibana
    version: "0.16.4"
    repository: https://kubernetes-charts.storage.googleapis.com
