apiVersion: v1
kind: Service
metadata:
  name: {{ template "referentiel-personnes-api.fullname" . }}-mongo
  labels:
    app: {{ template "referentiel-personnes-api.name" . }}-mongo
    chart: {{ template "referentiel-personnes-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: 27017
  selector:
    app: {{ template "referentiel-personnes-api.name" . }}-mongo
    release: {{ .Release.Name }}
