apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "evenement-parcours-integration.fullname" . }}-postgres
  labels:
    app: {{ template "evenement-parcours-integration.name" . }}-postgres
    chart: {{ template "evenement-parcours-integration.chart" . }}-postgres
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "evenement-parcours-integration.name" . }}-postgres
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "evenement-parcours-integration.name" . }}-postgres
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}-postgres:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
      - name: regsecret